#pragma once
#include <windows.h>
#include <mmsystem.h>
typedef WinCOM IDirectSound, *LPDIRECTSOUND, *LPDIRECTSOUND8, IDirectSoundBuffer, *LPDIRECTSOUNDBUFFER, *LPDIRECTSOUNDBUFFER8;
typedef struct { DWORD dwSize, dwFlags, dwBufferBytes, dwReserved; LPWAVEFORMATEX lpwfxFormat; GUID guid3DAlgorithm; } DSBUFFERDESC;
enum { DSBCAPS_PRIMARYBUFFER = 1, DSBCAPS_GLOBALFOCUS = 0x8000, DSBCAPS_GETCURRENTPOSITION2 = 0x10000,
	DSBCAPS_CTRLVOLUME = 0x80, DSBCAPS_LOCSOFTWARE = 8, DSSCL_PRIORITY = 2, DSSCL_NORMAL = 1,
	DSBPLAY_LOOPING = 1, DSBSTATUS_PLAYING = 1, DSBLOCK_ENTIREBUFFER = 2, DSBLOCK_FROMWRITECURSOR = 1 };
#define DSERR_BUFFERLOST ((HRESULT)0x88780096L)
