#!/usr/bin/env python3
"""gen_vt03_lut.py -- write src/vt03_palette_lut.h, the 4096-entry VT03 COLCOMP
colour table (12-bit colour number SSSS LLLL HHHH -> GBA BGR555).

The colours are Furbtendulator's (GFX.cpp, "Create VT03 palette") with its
default VT03Palette=0, the NTSC model: Furbtendulator is the colour reference
(MAINTAINERS_GUIDE s.79h, s.93).  Every float the C code stores is rounded to
float32 here, so the table matches furb_cli --dump-palette exactly; check with

    python3 tools/gen_vt03_lut.py --check DUMP.txt

The table it replaced was EmuVT's HSL2RGB.TAB (NESdev wiki, "VT03+ Enhanced
Palette"), kept in git history before s.93.
"""
import argparse
import math
import os
import struct


def f32(x):
    return struct.unpack('f', struct.pack('f', x))[0]


ALT_PHASES = (13, 7, 8, 9, 10, 11, 12, 1, 2, 3, 4, 5, 6, 0, 14, 15)


def vt03_rgb(i):
    """RGB888 of 12-bit colour number i, as Furbtendulator's Palette32."""
    phase, luma, chroma = i & 0xF, (i >> 4) & 0xF, (i >> 8) & 0xF
    if luma < (chroma + 1) >> 1 or luma > 15 - (chroma >> 1):   # inverted numbers
        phase = ALT_PHASES[phase]
        chroma = 16 - chroma
        luma = (luma - 8) & 0xF
    fluma = f32(luma / 15.0)
    fchroma = f32(chroma / 30.0)
    phase_offset = f32(0.0)                                     # VT03Palette=0 (NTSC)
    fphase = f32((((phase - 2) * 30.0) + phase_offset) * math.pi / 180.0)
    y, c = fluma, fchroma
    if phase == 0 or phase > 12:
        c = f32(0.0)
    if phase == 0:
        y = f32(y + fchroma)
    if phase == 13:
        y = f32(y - fchroma)
    if phase >= 14:
        y = f32(0.0)
    v = f32(math.sin(fphase) * c)
    u = f32(math.cos(fphase) * c)
    r = f32(y + 1.1400 * v + 0.0000 * u)
    g = f32(y - 0.5807 * v - 0.3940 * u)
    b = f32(y - 0.0000 * v + 2.0290 * u)
    k = 4.0 / 15.0
    r = f32((r - k) / (1.0 - k) * 15.0 / 13.0)
    g = f32((g - k) / (1.0 - k) * 15.0 / 13.0)
    b = f32((b - k) / (1.0 - k) * 15.0 / 13.0)
    if i == 0x0D0:
        r = g = b = f32(1.0)
    r = f32((r - 0.075) / 0.925)                                # VT03Palette != 1
    g = f32((g - 0.075) / 0.925)
    b = f32((b - 0.075) / 0.925)
    out = []
    for x in (r, g, b):
        x = min(max(x, 0.0), 1.0)
        out.append(int(x * 255.0))
    return out


def main():
    ap = argparse.ArgumentParser(description=__doc__.split('\n')[0])
    ap.add_argument('--check', help='furb_cli --dump-palette output to compare with')
    ap.add_argument('--out', default=os.path.join(os.path.dirname(__file__), '..', 'src', 'vt03_palette_lut.h'))
    a = ap.parse_args()
    rgb = [vt03_rgb(i) for i in range(4096)]
    if a.check:
        ref = {}
        for line in open(a.check):
            p = line.split()
            if len(p) == 3 and p[0] == 'vt03':
                ref[int(p[1], 16)] = int(p[2], 16)
        bad = [i for i in range(4096) if ref.get(i) != (rgb[i][0] << 16 | rgb[i][1] << 8 | rgb[i][2])]
        print('%d of 4096 entries differ from %s' % (len(bad), a.check))
        for i in bad[:10]:
            print('  %03X ours %02X%02X%02X ref %06X' % (i, rgb[i][0], rgb[i][1], rgb[i][2], ref.get(i, -1)))
        return 1 if bad else 0
    with open(a.out, 'w') as f:
        f.write('/* VT03+ COLCOMP colour table, generated by tools/gen_vt03_lut.py -- do not edit.\n'
                ' *\n'
                ' * Indexed by the 12-bit colour number (bits 11-6 from PPU $3F80+, bits 5-0\n'
                ' * from $3F00+): SSSS LLLL HHHH, saturation, luminance, hue.  The colours are\n'
                ' * Furbtendulator\'s NTSC model (GFX.cpp, VT03Palette=0), the project\'s colour\n'
                ' * reference (MAINTAINERS_GUIDE s.93).  BGR555 for GBA palette RAM; 8 KiB, so\n'
                ' * it stays in ROM, never IWRAM.\n'
                ' */\n\n'
                '#ifndef __VT03_PALETTE_LUT_H__\n#define __VT03_PALETTE_LUT_H__\n\n'
                'static const unsigned short vt03_palette_lut[4096] = {\n')
        for row in range(256):
            vals = []
            for i in range(row * 16, row * 16 + 16):
                r, g, b = rgb[i]
                vals.append('0x%04x' % ((r >> 3) | (g >> 3) << 5 | (b >> 3) << 10))
            f.write('    ' + ', '.join(vals) + ',\n')
        f.write('};\n\n#endif\n')
    print('wrote', os.path.normpath(a.out))
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
